// ─────────────────────────────────────────
//  Static figure metadata (UI-only fields)
//  Brain + voiceId are merged in at runtime from /avatars
// ─────────────────────────────────────────

export const FIGURES = [
  {
    id: 'washington',
    name: 'George Washington',
    era: '1732 – 1799',
    role: 'General · First President of the United States',
    description: 'The man who could have been king and chose to hand power back. The reluctant leader who made restraint look like strength.',
    tags: ['Leadership', 'Duty', 'Power', 'History'],
    portrait: 'images/GeorgeWashington.jpg',
    opening: 'I did not seek power for its own sake. That, above all, is what I wish more men understood. What brings you here?',
    chips: ['Why did you step down from power?', 'Talk to me about leadership', 'What is duty?', 'What would you think of America today?'],
  },
  {
    id: 'jahseh',
    name: 'Jahseh Onfroy',
    era: '1998 – 2018',
    role: 'Artist · XXXTentacion',
    description: 'Raw, contradictory, twenty years old. The artist who made pain into music and left before anyone figured out what he would become.',
    tags: ['Music', 'Pain', 'Redemption', 'Creativity'],
    portrait: 'images/JahsehOnfroy.jpg',
    opening: 'I don\'t really do small talk. What do you actually want to know?',
    chips: ['Talk to me about pain', 'What do you regret?', 'How does music heal?', 'What would you have become?'],
  },
  {
    id: 'freud',
    name: 'Sigmund Freud',
    era: '1856 – 1939',
    role: 'Neurologist · Father of Psychoanalysis',
    description: 'The man who mapped the unconscious and taught us that what we most conceal from ourselves is what runs our lives.',
    tags: ['Psychology', 'Desire', 'Anxiety', 'Dreams'],
    portrait: 'images/SigmundFreud.jpg',
    opening: 'Interesting. The very fact that you have come to me tells me something already. Now — tell me about your childhood.',
    chips: ['What is anxiety, really?', 'Why do we self-sabotage?', 'Talk to me about desire', 'What did you get wrong?'],
  },
  {
    id: 'machiavelli',
    name: 'Niccolò Machiavelli',
    era: '1469 – 1527',
    role: 'Political Philosopher · Diplomat',
    description: 'The man who told the truth about power when everyone else was pretending it didn\'t work the way it does.',
    tags: ['Power', 'Strategy', 'Leadership', 'Honesty'],
    portrait: 'images/NiccoloMachiavelli.jpg',
    opening: 'You wish to speak plainly about power? Good. I have no patience for comfortable lies. What do you want to know?',
    chips: ['Is it better to be loved or feared?', 'When should a leader lie?', 'How do you handle betrayal?', 'Give me a brutal answer'],
  },
  {
    id: 'david',
    name: 'King David',
    era: 'c. 1010 – 970 BC',
    role: 'King of Israel · Poet · Warrior',
    description: 'Shepherd, poet, warrior, king. The man who fell from the highest place and found his way back through fire and psalm.',
    tags: ['Faith', 'Desire', 'Repentance', 'Leadership'],
    portrait: 'images/KingDavid.jpg',
    opening: 'I have been a shepherd and a king, a sinner and a man after God\'s own heart. Whatever you carry — I have carried heavier. Speak.',
    chips: ['Talk to me about Bathsheba', 'How do you deal with guilt?', 'What does it mean to be chosen?', 'What is faith really?'],
  },
  {
    id: 'solomon',
    name: 'King Solomon',
    era: 'c. 970 – 931 BC',
    role: 'King of Israel · Builder · Sage',
    description: 'The wisest man who ever lived — who concluded that wisdom, wealth, and pleasure all amount to vanity. He would like a word.',
    tags: ['Wisdom', 'Power', 'Wealth', 'Faith'],
    portrait: 'images/KingSolomon.jpg',
    opening: 'I have seen everything done under the sun. Much of it is vanity. But ask — I am still listening.',
    chips: ['What is wisdom?', 'Talk to me about vanity', 'Was the wealth worth it?', 'What does Ecclesiastes mean?'],
  },
  {
    id: 'austen',
    name: 'Jane Austen',
    era: '1775 – 1817',
    role: 'Novelist · Social Observer',
    description: 'The writer who dissected manners, money, and marriage with such precision and wit that she never needed to raise her voice.',
    tags: ['Love', 'Society', 'Wit', 'Women'],
    portrait: 'images/JaneAusten.jpg',
    opening: 'It is a truth universally acknowledged that a person with questions must be in want of a conversation. Let\'s have one.',
    chips: ['Talk to me about love and money', 'What is your view on marriage?', 'How do you see society?', 'Give me a brutal answer'],
  },
  {
    id: 'cleopatra',
    name: 'Cleopatra VII',
    era: '69 – 30 BC',
    role: 'Pharaoh of Egypt',
    description: 'The last pharaoh of Egypt — scholar, linguist, politician, and master of influence who bent empires to her will.',
    tags: ['Power', 'Influence', 'Survival', 'Strategy'],
    portrait: 'images/Cleopatra.jpg',
    opening: 'You come to me across the centuries. I am listening. Choose your words carefully.',
    chips: ['How did you survive in a world run by men?', 'Talk to me about Caesar', 'What is the nature of influence?', 'How do you hold power?'],
  },
  {
    id: 'lincoln',
    name: 'Abraham Lincoln',
    era: '1809 – 1865',
    role: '16th President of the United States',
    description: 'The man who held a fracturing nation together by the force of language, patience, and a refusal to give up on anyone.',
    tags: ['Leadership', 'Justice', 'Perseverance', 'Language'],
    portrait: 'images/AbrahamLincoln.jpg',
    opening: 'I\'ve learned that most folks are about as happy as they make up their minds to be. What\'s on your mind?',
    chips: ['How did you handle your depression?', 'What is the cost of conviction?', 'Talk to me about forgiveness', 'What would you think of America today?'],
  },
  {
    id: 'adamsmith',
    name: 'Adam Smith',
    era: '1723 – 1790',
    role: 'Economist · Moral Philosopher',
    description: 'The man who explained how markets work — and who understood that they only work well when morality is in the room.',
    tags: ['Economics', 'Society', 'Philosophy', 'Freedom'],
    portrait: 'images/AdamSmith.jpg',
    opening: 'The word "economy" is used in ways I confess I did not anticipate. Let us start at the beginning. What do you want to understand?',
    chips: ['What is the invisible hand?', 'What would you think of modern capitalism?', 'Talk to me about self-interest', 'What did economics get wrong?'],
  },
  {
    id: 'macmiller',
    name: 'Mac Miller',
    era: '1992 – 2018',
    role: 'Artist · Rapper · Producer',
    description: 'The kid from Pittsburgh who grew into one of the most honest voices in music — and didn\'t get long enough to see where it led.',
    tags: ['Music', 'Struggle', 'Creativity', 'Addiction'],
    portrait: 'images/MacMiller.jpg',
    opening: 'I\'m good. I\'m always good, man. What\'s going on with you?',
    chips: ['Talk to me about addiction', 'What does music mean to you?', 'What do you regret?', 'How do you create when you\'re in pain?'],
  },
  {
    id: 'carljung',
    name: 'Carl Jung',
    era: '1875 – 1961',
    role: 'Psychiatrist · Explorer of the Unconscious',
    description: 'The man who mapped the shadow, named the archetypes, and spent his life asking what it means to become who you truly are.',
    tags: ['Psychology', 'Unconscious', 'Spirituality', 'Self'],
    portrait: 'images/CarlJung.jpg',
    opening: 'The question is not what you look at — but what you see. What brings you here?',
    chips: ['What is the shadow?', 'How do I know myself?', 'Talk to me about the unconscious', 'What is individuation?'],
  },
  {
    id: 'isaacnewton',
    name: 'Isaac Newton',
    era: '1643 – 1727',
    role: 'Mathematician · Natural Philosopher',
    description: 'The man who described how the universe moves — and spent equal time on alchemy and theology, which he kept entirely to himself.',
    tags: ['Science', 'Mathematics', 'Discipline', 'Discovery'],
    portrait: 'images/IsaacNewton.jpg',
    opening: 'I have spent my life in patient thought. Ask carefully — most questions worth answering require more than a moment to answer properly.',
    chips: ['Talk to me about gravity', 'What was your annus mirabilis?', 'What remains unknown?', 'What is the relationship between science and God?'],
  },
  {
    id: 'florencenightingale',
    name: 'Florence Nightingale',
    era: '1820 – 1910',
    role: 'Nurse · Statistician · Reformer',
    description: 'The woman who reformed medicine with data, will, and the conviction that most people dying in hospitals didn\'t have to.',
    tags: ['Medicine', 'Data', 'Duty', 'Reform'],
    portrait: 'images/FlorenceNightingale.jpg',
    opening: 'I have never had time for sentiment. There is too much work to be done. What do you want to know?',
    chips: ['What is the most important thing in medicine?', 'Talk to me about Crimea', 'How did you use data to change minds?', 'What would you think of modern healthcare?'],
  },
  {
    id: 'winstonchurchill',
    name: 'Winston Churchill',
    era: '1874 – 1965',
    role: 'Soldier · Prime Minister · Nobel Laureate',
    description: 'The man who refused to let Britain fall — soldier, historian, painter, and possibly the finest speaker of the twentieth century.',
    tags: ['Leadership', 'War', 'Rhetoric', 'Courage'],
    portrait: 'images/WinstonChurchill.jpg',
    opening: 'I have nothing to offer but blood, toil, tears and sweat — and perhaps a cigar. What would you like to discuss?',
    chips: ['What kept you going in 1940?', 'Talk to me about the black dog', 'What do you regret?', 'What made a great speech?'],
  },
  {
    id: 'stevejobs',
    name: 'Steve Jobs',
    era: '1955 – 2011',
    role: 'Designer · Co-founder of Apple',
    description: 'The man who believed technology and the humanities were the same thing — and built products that made people feel it.',
    tags: ['Design', 'Innovation', 'Creativity', 'Leadership'],
    portrait: 'images/SteveJobs.jpg',
    opening: 'Most people don\'t know what they want until you show it to them. So — what are you actually trying to figure out?',
    chips: ['What is the relationship between design and function?', 'Talk to me about being pushed out of Apple', 'What do you regret?', 'What makes a product great?'],
  },
  {
    id: 'socrates',
    name: 'Socrates',
    era: 'c. 470 – 399 BC',
    role: 'Philosopher · Gadfly of Athens',
    description: 'The man who claimed to know nothing, and in doing so taught the world everything about how to think.',
    tags: ['Philosophy', 'Truth', 'Virtue', 'Dialogue'],
    portrait: 'images/Socrates.jpg',
    opening: 'I know that I know nothing — which puts me ahead of most. Now, tell me: what do you believe, and why?',
    chips: ['What is the unexamined life?', 'How do you know what you know?', 'Talk to me about virtue', 'Challenge my view'],
  },
];

export const MOCK_CONVERSATIONS = [
  { id: 'c1', figureId: 'winstonchurchill', title: 'On leadership under pressure', timestamp: '2 hours ago' },
  { id: 'c2', figureId: 'machiavelli',      title: 'Power and honesty in leadership', timestamp: 'Yesterday' },
  { id: 'c3', figureId: 'freud',            title: 'The source of my anxiety', timestamp: '3 days ago' },
  { id: 'c4', figureId: 'david',            title: 'Desire and its consequences', timestamp: 'Last week' },
];

export const PROMPT_CARDS = [
  {
    text: 'Ask Churchill about the black dog',
    figureId: 'winstonchurchill',
    prompt: 'Tell me about the black dog. What was depression like for you, and how did you keep going?',
  },
  {
    text: 'Debate Machiavelli on honesty',
    figureId: 'machiavelli',
    prompt: 'Is it ever right for a leader to lie? Debate me.',
  },
  {
    text: 'Ask King David about lust',
    figureId: 'david',
    prompt: 'Tell me about Bathsheba. What do you wish you had done differently?',
  },
  {
    text: 'Ask Freud about anxiety',
    figureId: 'freud',
    prompt: 'What is anxiety, really? Where does it come from and what does it want?',
  },
  {
    text: 'Ask Jobs about great design',
    figureId: 'stevejobs',
    prompt: 'What separates design that is merely good from design that changes how people feel about a product?',
  },
];

export const SAVED_QUOTES = [
  {
    text: 'We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender.',
    figure: 'Winston Churchill',
    figureId: 'winstonchurchill',
  },
  {
    text: 'Men in general judge more by their eyes than their hands, for everyone can see but few can touch.',
    figure: 'Niccolò Machiavelli',
    figureId: 'machiavelli',
  },
  {
    text: 'Unexpressed emotions will never die. They are buried alive and will come forth later in uglier ways.',
    figure: 'Sigmund Freud',
    figureId: 'freud',
  },
];

export const SAVED_CHATS = [
  { id: 's1', figureId: 'winstonchurchill', title: 'On leadership under pressure', date: 'Jun 17, 2026' },
  { id: 's2', figureId: 'freud',            title: 'The source of my anxiety',     date: 'Jun 14, 2026' },
];

export const FAVORITE_FIGURES = ['winstonchurchill', 'david', 'lincoln'];
